# version: '3.8' <-- not needed

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root # Your password
      MYSQL_DATABASE: coffee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    # 👇 ADD THIS HEALTHCHECK BLOCK 👇
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend Service
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    # Your original command is fine now
    command: sh -c "npm run seed && npm run start"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: # Your password
      DB_NAME: coffee_db
      PORT: 3000
      MYSQL_ROOT_PASSWORD: root
    # 👇 MODIFY depends_on LIKE THIS 👇
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

# ... (frontend and volumes sections are unchanged) ...
  # Angular Frontend Service
  frontend:
    build:
      context: . # Build context is the root of the project
      dockerfile: public/coffee-bean-dream-public/Dockerfile # Path to the frontend Dockerfile
    ports:
      - "80:80" # Map host port 80 to container port 80 (standard HTTP port)
    depends_on:
      - backend # Ensure backend starts before frontend (optional, but good for local dev)
    restart: unless-stopped

volumes:
  mysql_data: # Define the named volume for MySQL data persistence