services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'  # ✅ Allow empty password
      MYSQL_DATABASE: coffee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root"]  # ✅ No password here
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend Service
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "npm run seed && npm run server-dev"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ""         # ✅ Explicitly empty
      DB_NAME: coffee_db
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  # Angular Frontend Service
  frontend:
    build:
      context: .
      dockerfile: public/coffee-bean-dream-public/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
